### ISSUE TITLE
Add link to github pages

### ISSUE THREAD

**Issue by nfischer** [kalhauge/ash#1]
Now that you're using github pages, you should edit the description at the top of the main page of the repo to include the URL https://kalhauge.github.io/ash/. Too bad github isn't smart enough to do this for us.

...or better yet, add in a README based off your design doc (that includes the URL at the top)!

**Comment by kalhauge** [comment]
Great idea :) ! So far is there more focus on prototyping so design documents comes second.

**Comment by nfischer** [comment]
:+1:
